### PR TITLE
Merge Develop to Master for 2.0.2 release

### PR DESCRIPTION
**Pull request by knelson-farmbeltnorth**

### CODE REVIEW

**Comment by knelson-farmbeltnorth** [comment]
Merging per agreement at previous ADAPT technical meeting

**Comment by stevehipwell** [comment]
@knelson-farmbeltnorth - Moving forward, changes to the ADAPT data model would need to be reflected in a corresponding change to the ADM plugin. As the new version of the ADM plugin has not been pulled yet this isn't possible and I'm only mentioning it here so we have a record. I'll make a change to my pull request to add context items to load.

**Comment by stevehipwell** [comment]
@knelson-farmbeltnorth - Reflecting on my comment about the data model change in this release, I think the correct version for this release should actually have been 2.1.0 if we're following semver. The rationale behind this is that a new property has been introduced to a public interface `Load.ContextItems`.

**Comment by stevehipwell** [comment]
@knelson-farmbeltnorth - Sorry for the comment spam. Somehow I'd forgotten that the new version had been pulled just not released. I've created a pull request (https://github.com/ADAPT/ADMPlugin/pull/47) for the required changes.

**Pull request merged**
