### PR TITLE
Embed XML resources directly in assembly

### PR DESCRIPTION
**Pull request by stevehipwell**
In the v2 release the ability to specify an alternate location for the representation and unit XML definition files was added. In adding this code .NET Core support was broken. This needs to be fixed both for the ability to use the ADAPT Framework on .NET Core as well as the ability to work on the ADM Plugin (failing unit tests).

I think that the quickest and safest solution, to both the bug introduced in v2 and the ongoing complexity around how to identify the location of the XML files, is to embed them inside the assembly. I believe the need to have the XML files external to the assembly is unnecessary and potentially dangerous for the ADAPT ecosystem. If the files are external then they can replaced with non-standard versions which could cause problems, as this isn't a current use case it mould make sense to remove it before it is abused. Also with the ease of patch releasing ADAPT, having the XML able to be updated independently to the packages would seem to be redundant especially as there is not current protocol for this scenario.

Note - This is my preferred alternative to pull request https://github.com/ADAPT/ADAPT/pull/224.

### CODE REVIEW

**Comment by knelson-farmbeltnorth** [comment]
@stevehipwell @strhea and I agreed to merge 224 in the short term, so we can publish a 2.0.1 framework and release the updated ISO Plugin with the fix for .Net Core.    We need to discuss 226 in the next technical meeting and can potentially release another framework update for that if approved by the group.

**Comment by knelson-farmbeltnorth** [comment]
For clarity, I was writing to @stevehipwell vs. including him in the decision made by @strhea and I.

**Comment by stevehipwell** [comment]
Thanks @knelson-farmbeltnorth, I was just about to get stuck on testing the ADM plugin changes without this.

**Comment by aferreyra** [comment]
I think am important part of having the representation data separate from the assembly was that it provided us the ability to add representations, enumerated items, etc. without having to release a new version. In a perfect, hopefully-to-happen-in-the-not-too-distant-future  world, these resources would be provided via an API. Stuart and I are working to propose a design for this.

**Comment by aferreyra** [comment]
Regarding the matter of establishing a protocol to add resources, that's one of the motivations for standing up the Controlled Vocabularies Working Group (under AgGateway's Standards & Guidelines Committee). The request for participation for that group was distributed recently.

**Comment by stevehipwell** [comment]
@aferreyra - I agree that in an ideal world representations and units could be dynamically added. However before this can happen the system needs to be designed to actually handle this workflow. For example if you persist data today with ADM and then try and load it back up with changed representations you would have a problem. The idea behind embedding the resources is to stop people making bad decisions now while a working design is considered. It also helps with the current pain around loading XML resources.

My preference for the design around both units and representations is that the component has enough data embedded inside it to work, with the ability to augment the base units/representations from an API or a file. I would also like to see the merging of representation and context item as I think there is currently a duplication of concerns.

I've already started to have a look at some of these concepts and would be interested to see what other ideas there are out there?

**Pull request closed without merging**
