### PR TITLE
Use Assembly.CodeBase instead of AppDomain.CurrentDomain.BaseDirectory when loading resources.

### PR DESCRIPTION
**Pull request by dmTech04**
As noted here [https://github.com/xunit/xunit/issues/179#issuecomment-60145105](url), using AppDomain.CurrentDomain.BaseDirectory. BaseDirectory to load resource files causes problems with shadow copy which xUnit tests use by default.   

This PR creates a ResourcePathUtil class which uses Assembly.CodeBase instead.  Then changes RepresentationManager and UnitSystemManager to use it.  

Since this project uses NUnit, I added the ResourcePathUtil test which compares the 2 versions.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@dmTech04 - From memory `Assembly.CodeBase` will not work for .NET Core when the assembly is referenced from NuGet. As the current tests are all passing could you explain the actual problem with `AppDomain.CurrentDomain.BaseDirectory`?

**Comment by dmTech04** [comment]
@stevehipwelln - Thanks, I'll check on Nuget with .NET Core.  

The issue with BaseDirectory is when running xUnit tests in our project that references the ADAPT Nuget. We use xUnit and by default it uses shadow copy.  That results in the units & reference xml files not being in the directory that the dll gets shadow copied to.  So anything needing units/reference fails when it tries to load them.  Disabling shadow copy allows the test to run successfully.  

After looking at the .Net core/nuget issue, if things still seem doable with CodeBase, I can add an xUnit test to show the error.

**Comment by stevehipwell** [comment]
@dmTech04 - I did spend a long time looking at the best way to reference the resources and `CodeBase` was by far and away the best solution.

Are you referring to an error that you have in a separate assembly referencing the ADAPT Framework? If that is the case, both the ADM Plugin and ISO Plugin are able to be tested successfully.

**Comment by dmTech04** [comment]
@stevehipwell , yes.  I had a library referencing ADAPT Framework.  In the unit tests for that library, I was testing something which used units, and those xUnit tests were failing since the directory the ADAPT dll was shadow copied to didn't have the resources/*.xml files.  

What I I think is key, though, is I was running the tests via Resharper rather than VS.  I believe Resharper runs things in an external process, which causes xUnit to use shadow copy.  When I configured xUnit not to use shadowCopy those tests ran fine.

However, since then I stopped using Resharper's test runner and now the same tests run fine in VS test runner even without the config disabling shadowCopy.  However, others on our team still use the Resharper test runner.  I'll check with them tomorrow and see if this is still an issue for them.  I'm not sure how big an issue it would be to leave shadowCopy false for these specific tests.

So, your tests for the ADM Plugins would fine, since I assume they are also nUnit not xUnit, and also are probably not being run with Resharper.  

Given your time looking into the resource loading and preference for the current approach, it may be best to leave things as is.  I'll let you know what I find out. 

Thanks,
Keith

**Comment by stevehipwell** [comment]
@dmTech04 - You could always have a set of resources in your unit test project that you copy to `CodeBase` as part of the setup.

**Comment by dmTech04** [comment]
Thanks @stevehipwell tests run fine for everyone now.  I'll go ahead and close this one.  Sorry for the trouble.  :)

**Pull request closed without merging**
